routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::resource('courses', App\Http\Controllers\CourseController::class)->middleware('auth');

Route::get('teachers', [App\Http\Controllers\TeacherController::class, 'index'])->name('teachers.index')->middleware('auth');

app/Models/Course.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Course extends Model
{
    use HasFactory;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'state',
    ];

    /**
     * Relation one to many (inverse) with Teacher
     */
    public function teacher()
    {
        return $this->belongsTo('App\Models\Teacher');
    }

     /**
     * Relation many to many with Student
     */
    public function students()
    {
        return $this->belongsToMany('App\Models\Student');
    }
}

app/Http/Controllers/CourseController.php
<?php

namespace App\Http\Controllers;

use App\Models\Course;
use App\Models\Teacher;
use App\Models\User;
use Illuminate\Http\Request;

class CourseController extends Controller
{
    public function index(){
        $role = $this->getRole();
        $teacher = Teacher::where(['user_id' => auth()->user()->id])->first();
        $courses = Course::where(['teacher_id' => $teacher->id])->get();
        return view('course.index', compact('courses', 'role'));
    }

    /**
     * Create course
     */
    public function create()
    {
        $role = $this->getRole();
        $teacher_id = $teacher = Teacher::where(['user_id' => auth()->user()->id])->first()->id;
        return view('course.create', compact('teacher_id', 'role'));
    }

    /**
     * Save course
     */
    public function store(Request $request)
    {
        $course = Course::create($request->all());
        $course->teacher_id = $request->all()['teacher_id'];
        $course->save();
        return redirect()->route('courses.index', $course);
    }

    /**
     * Show view edit course
     */
    public function edit(Course $course)
    {
        $role = $this->getRole();
        return view('course.edit', compact('course', 'role'));
    }

    /**
     * Edit course
     */
    public function update(Request $request, Course $course)
    {
        $course->name = $request->name;
        $course->state = $request->state;
        $course->save();
        
        return redirect()->route('courses.index', $course);
    }

    /**
     * Delete course
     */
    public function destroy(Course $course)
    {
        $course->delete();

        return redirect()->route('courses.index');
    }

    /**
     * Get role of user
     */
    public function getRole()
    {
        $user = User::find((auth()->user()->id));

        if ($user->role == 'administrador') {
            $role = 'administrador';
        }elseif (is_null($user->teacher)) {
            $role = 'consumidor';
        }else{
            $role = 'creador';
        }

        return $role;
    }
}

resources/views/course/create.blade.php
@extends('layouts.app')

@section('content')

<div class="grid grid-cols-1 place-items-center mt-12 mb-4">
    <h1 class="text-gray-700 text-3xl font-bold text-center mb-8">Crear curso</h1>
    <form action="{{ route('courses.store') }}" method="post" class="md:w-1/3 w-full pr-12 pl-12">
        @csrf
        <label for="" class="block mb-2 text-sm font-medium text-gray-800">Nombre</label>
        <input type="text" name="name" id="" value="{{ old('name') }}" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5">
        @error('name')
            <small class="text-red-700">{{ $message }}</small>
        @enderror        
        <label for="" class="block mb-2 text-sm font-medium text-gray-800">Estado</label>
        <select name="state" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5" required="">
            <option value="activo">activo</option>
            <option value="inactivo">inactivo</option>                        
        </select>  
        @error('state')
            <small class="text-red-700">{{ $message }}</small>
        @enderror      
        <input type="hidden" name="teacher_id" value="{{ $teacher_id }}">
        <button type="submit" class="text-white bg-gray-800 hover:bg-gray-500 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center mt-5">Grabar</button>
    </form>
</div>
@endsection

resources/views/course/edit.blade.php
@extends('layouts.app')

@section('content')

<div class="grid grid-cols-1 place-items-center mt-12 mb-4">
    <h1 class="text-gray-700 text-3xl font-bold text-center mb-8">Editar curso</h1>
    <form action="{{ route('courses.update', $course) }}" method="post" class="md:w-1/3 w-full pr-12 pl-12">
        @csrf
        @method('put')
       
        <label for="" class="block mb-2 text-sm font-medium text-gray-800">Nombre</label>
        <input type="text" name="name" id="" value="{{ $course->name }}" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5">               
        
        <label for="" class="block mb-2 text-sm font-medium text-gray-800">Estado</label>
        <select name="state" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5" required="">
            <option value="activo" {{ $course->state == "activo" ? 'selected' : '' }}>activo</option>
            <option value="inactivo" {{ $course->state == "inactivo" ? 'selected' : '' }}>inactivo</option>                        
        </select> 
                
        <button type="submit" class="text-white bg-gray-800 hover:bg-gray-500 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center mt-5">Grabar</button>
    </form>
</div>
@endsection

resources/views/course/index.blade.php
@extends('layouts.app')

@section('content')
<div class="grid grid-cols-1 place-items-center mt-12 mb-4">
    <h1 class="text-gray-700 text-3xl font-bold text-center mb-8">Listado de cursos</h1>
    <div class="relative overflow-x-auto shadow-md sm:rounded-lg">
        <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
            <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                <tr>
                    <th scope="col" class="px-6 py-3">
                        Nombre
                    </th>
                    <th scope="col" class="px-6 py-3">
                        Estado
                    </th>
                    <th scope="col" class="px-6 py-3">
                        Acciones
                    </th>                    
                </tr>
            </thead>
            <tbody>                
                @foreach ($courses as $course)
                <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
                    <th scope="row" class="px-6 py-4 font-medium text-gray-900 dark:text-white whitespace-nowrap">
                        {{ $course->name }}
                    </th>
                    <td class="px-6 py-4">
                        {{ $course->state }}
                    </td>                   
                    <td class="px-6 py-4">
                        <a href="{{ route('courses.edit', $course) }}">Editar</a>
                        <form action="{{ route('courses.destroy', $course) }}" method="post">
                            @csrf
                            @method('delete')
                            <button type="submit">Eliminar</button>
                        </form>
                    </td>                    
                </tr> 
                @endforeach            
            </tbody>
        </table>
    </div>
    <a href="{{ route('courses.create') }}" class="text-white bg-gray-800 hover:bg-gray-500 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center mt-5">Crear curso</a>
</div>
@endsection